---
title: "p8105_hw2_xh2636"
author: "Xiaoyu Huang"
date: "2023-09-28"
output: html_document
---

## Problem 1
```{r}
library(tidyverse)
library(dplyr)
```

## P1-First part
```{r}
pols_month_data = read_csv("./data/pols-month.csv")%>%
  janitor::clean_names()%>%
  separate(mon, into = c("year","month","day"),
           sep = "-", convert = TRUE) %>% 
  mutate(month = recode(month, "1" = "January", "2" = "February", "3" = "March", 
                        "4" = "April", "5" = "May", "6" = "June", "7" = "July", 
                        "8" = "August","9" = "September", "10" = "October", 
                        "11" = "November", "12" = "December"))%>%
  mutate(president = recode(.x = prez_dem, '0' = "gop", '1' = "dem"))%>%
  select(-prez_dem, -prez_gop, -day)%>%
  relocate(year, month)
```

## P1-Second part
```{r}
snpdata = read_csv("./data/snp.csv")%>%
separate(date, into = c("month", "day","year"), sep = "/", convert = TRUE)%>%
mutate(month = recode(month, "1" = "January", "2" = "February", "3" = "March", 
                        "4" = "April", "5" = "May", "6" = "June", "7" = "July", 
                        "8" = "August","9" = "September", "10" = "October", 
                        "11" = "November", "12" = "December"))%>%
mutate(year = as.numeric(year)) %>%
  mutate(year = ifelse(year > 49, year + 1900, year + 2000))%>%
select(-day)%>%
  relocate(year, month)
```

## P1-Third part


