p8105_hw2_xh2636
================
Xiaoyu Huang
2023-09-28

## Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(dplyr)
library(readxl)
```

## P1-1st part

``` r
pols_month_data = read_csv("./data/pols-month.csv")%>%
  janitor::clean_names()%>%
  separate(mon, into = c("year","month","day"),
           sep = "-", convert = TRUE) %>% 
  mutate(month = recode(month, "1" = "January", "2" = "February", "3" = "March", 
                        "4" = "April", "5" = "May", "6" = "June", "7" = "July", 
                        "8" = "August","9" = "September", "10" = "October", 
                        "11" = "November", "12" = "December"))%>%
  mutate(president = recode(.x = prez_dem, '0' = "gop", '1' = "dem"))%>%
  select(-prez_dem, -prez_gop, -day)%>%
  relocate(year, month, president)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
view(pols_month_data)
```

For the first data set ‘pols_month_data’, we have 822 rows and 9
columns. The range for this data set is 1947-2015, which contain
important information related to the number of national politicians who
are democratic or republican at any given time. The key variable is
create a president variable taking values “gop” and “dem”.

## P1-2nd part

``` r
snpdata = read_csv("./data/snp.csv")%>%
separate(date, into = c("month", "day","year"), sep = "/", convert = TRUE)%>%
mutate(month = recode(month, "1" = "January", "2" = "February", "3" = "March", 
                        "4" = "April", "5" = "May", "6" = "June", "7" = "July", 
                        "8" = "August","9" = "September", "10" = "October", 
                        "11" = "November", "12" = "December"))%>%
mutate(year = as.numeric(year)) %>%
  mutate(year = ifelse(year > 49, year + 1900, year + 2000))%>%
select(-day)%>%
  relocate(year, month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
view(snpdata)
```

For the second data set “snpdata”, we have 787 rows and 2 columns. The
range for this data set is 1950-2015, which contain the date of the
observation and the closing values of the S&P stock index on the
associated date.

## P1-3rd part

``` r
unemploydata = read_csv("./data/unemployment.csv")%>%
janitor::clean_names()%>%
  pivot_longer(cols = jan:dec,
               names_to = "month",
               values_to = "Percentage_of_unemployment")%>%
mutate(month = recode(month, "jan" = "January", "feb" = "February", 
                      "mar" = "March", "apr" = "April", "may" = "May", "jun" = "June", 
                      "jul" = "July", "aug" = "August", "sep" = "September", 
                      "oct" = "October","nov" = "November", "dec" = "December"))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
view(unemploydata)
```

## Binding Data

``` r
merge_data = left_join(pols_month_data, snpdata,
                       by = c("year", "month"))%>%
  left_join(unemploydata, by = c("year", "month"))%>%
relocate(year, month, president)
view(merge_data)
```

For the third data set “unemploydata”, we have 68 rows and 13 columns.
The range for this data set is 1948-2015, which contain the year of the
measurements and percentage of unemployment in the particular month of
the associated year. The result is that after organizing these data in
various ways, such as arranging them by year and month, etc., we can
integrate three different excel data for easy viewing.

## Problem 2

``` r
MrTrashdata = readxl::read_excel("./data/202309 Trash Wheel Collection Data.xlsx",
                                 sheet = "Mr. Trash Wheel",
                                 range = "A2:N586")%>%
  janitor::clean_names()%>%
  drop_na()%>%
  mutate(homes_powered = (weight_tons * 500)/30)
MrTrashdata$date <- substr(MrTrashdata$date, 
                           nchar(MrTrashdata$date) - 1, nchar(MrTrashdata$date))
view(MrTrashdata)
```

``` r
ProTrashdata = readxl::read_excel("./data/202309 Trash Wheel Collection Data.xlsx",
                                 sheet = "Professor Trash Wheel",
                                 range = "A2:M108")%>%
  janitor::clean_names()%>%
  mutate(homes_powered = (weight_tons * 500)/30)
ProTrashdata$date <- substr(ProTrashdata$date, 
                           nchar(ProTrashdata$date) - 1, nchar(ProTrashdata$date))
view(ProTrashdata)
Trash_weight_sum <- sum(ProTrashdata$weight_tons)
```

``` r
Gwyndata = readxl::read_excel("./data/202309 Trash Wheel Collection Data.xlsx",
                                 sheet = "Gwynnda Trash Wheel",
                                 range = "A2:L157")%>%
  janitor::clean_names()%>%
  drop_na()%>%
  mutate(homes_powered = (weight_tons * 500)/30)
Gwyndata$date <- substr(Gwyndata$date, 
                           nchar(Gwyndata$date) - 1, nchar(Gwyndata$date))
view(Gwyndata)
```

## Find the total cigarette butts

``` r
Gwyndata_abc = readxl::read_excel("./data/202309 Trash Wheel Collection Data.xlsx",
                                  sheet = "Gwynnda Trash Wheel",
                                  range = "I2:I7")
sum_cigarette <- sum(Gwyndata_abc$`Cigarette Butts`)
```

## Binding data

``` r
Mr_Trash_Wheel <- MrTrashdata %>%
  mutate(wheel_name = "Mr. Trash Wheel")
Professor_Trash_Wheel <- ProTrashdata %>%
  mutate(wheel_name = "Professor Trash Wheel")
Gwynna_Trash_Wheel <- Gwyndata %>%
  mutate(wheel_name = "Gwynna Trash Wheel")
Mr_Trash_Wheel$year <- as.numeric(Mr_Trash_Wheel$year)
Professor_Trash_Wheel$year <- as.numeric(Professor_Trash_Wheel$year)
Gwynna_Trash_Wheel$year <- as.numeric(Gwynna_Trash_Wheel$year)
combined <- bind_rows(Mr_Trash_Wheel, Professor_Trash_Wheel, Gwynna_Trash_Wheel)
drop_na(combined)
```

    ## # A tibble: 584 × 15
    ##    dumpster month  year date  weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <chr> <dbl> <chr>       <dbl>              <dbl>           <dbl>
    ##  1        1 May    2014 16           4.31                 18            1450
    ##  2        2 May    2014 16           2.74                 13            1120
    ##  3        3 May    2014 16           3.45                 15            2450
    ##  4        4 May    2014 17           3.1                  15            2380
    ##  5        5 May    2014 17           4.06                 18             980
    ##  6        6 May    2014 20           2.71                 13            1430
    ##  7        7 May    2014 21           1.91                  8             910
    ##  8        8 May    2014 28           3.7                  16            3580
    ##  9        9 June   2014 05           2.52                 14            2400
    ## 10       10 June   2014 11           3.76                 18            1340
    ## # ℹ 574 more rows
    ## # ℹ 8 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   sports_balls <dbl>, homes_powered <dbl>, wheel_name <chr>

``` r
view(combined)
```

The Mr.Trash Wheel key variables are different kind of bags, ‘glass
bottles’, ‘plastic bottles’, and sport balls. For the Professor trash
wheel, the key variable are also the same as before but no sport balls.
For the Gwynna trash wheel, the variable are also same but without
sports balls, chip bags, grocery bags, and glass bottle. The dumpster
number, trash weight, and home powered are important for all the trash
wheels. The total weight of trash collected by Professor Trash Wheel is
216.26 tons, and the total number of cigarette butts collected by
Gwynnda in July of 2021 is 1.63^{4}.

## Probelm 3

## P3-1st part

``` r
MCI = read_csv("./data/MCI_baseline.csv", skip = 1)%>%
janitor::clean_names()
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
MCI$sex <- ifelse(MCI$sex == 1, "Male", "Female")
MCI$apoe4 <- ifelse(MCI$apoe4 == 1, "Apoe4 carrier", "Non-Apeo4 carrier")


MCI <- MCI %>%
  subset(current_age < age_at_onset|age_at_onset ==".")
view(MCI)
```

First I chose the path to read the document, and used Janitor to modify
the name of the document, and I used “skip=1” to skip reading the name
of the first line, because that is not what we want. The second line is
the title. After this I used “ifelse” to classify files of type 0 and 1
and give the corresponding numbers different names. Then I used “%in%”
to filter out rows that were not data in the age on set. And this data
includes age, gender, education and whether you are a carrier of apoe4.
They are 483 participants were recruited and 97 developed MCI.

The average age for this MCI is 65.0286013. The number of total people
is 210. The number of total female apoe4 carrier is 63. So the
proportion of women in the study are APOE4 carriers is 0.3.

## P3-2nd part

``` r
Amyloid = read_csv("./data/mci_amyloid.csv", skip = 1)%>%
  janitor::clean_names()%>%
  pivot_longer(baseline:time_8,
             names_to = "time",
             values_to = "time_value") # using pivot long to change the formate of the document.
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
colnames(Amyloid)[which(colnames(Amyloid) == "study_id")] <- "id"
  view(Amyloid)
```

Same as the previous data, I chose the path to read the document, and
used Janitor to modify the name of the document, and I used “skip=1” to
skip reading the name of the first line, because that is not what we
want. The second line is the title. Then I used drop na to delete the
rows with NA, and Na occurred in this data, so I had to eliminate by
using !grepl(pattern, x), which is used to filter out elements in the
character vector x that do not match the specified pattern. Then the Na
in each row is disappeared. This data contains the elapsed time (in
years) from study baseline to the visit where the biomarker amyloid
42/40 ratio was measured and four different time points.

## P3-3rd part

## Merge data

``` r
combined_df <- inner_join(MCI, Amyloid, by = "id")
view(combined_df)
```

``` r
count_female = combined_df %>% group_by(sex) %>% filter(sex=="Female") %>% summarize(n=n())
count_female
```

    ## # A tibble: 1 × 2
    ##   sex        n
    ##   <chr>  <int>
    ## 1 Female  1025

``` r
count_man = combined_df %>% group_by(sex) %>% filter(sex=="Male") %>% summarize(n=n())
count_man
```

    ## # A tibble: 1 × 2
    ##   sex       n
    ##   <chr> <int>
    ## 1 Male   1330

The combine_df included all the participants (483) appear in both the
baseline or Amyloid datasets, and rest of the “id”, which is not
included are participate whether in baseline and Amyloid. The combine_df
age mean is 65.0475584, and the education mean is 16.3821656. Also, the
man and female in this data are both 33.

``` r
file_path <- "./data/combined_data.csv"
write.csv(combined_df, file = file_path, row.names = FALSE)
cat("Combined data has been exported to", file_path, "\n")
```

    ## Combined data has been exported to ./data/combined_data.csv
